version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8080:3000"          # host:container
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"          # Vite frontend
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:

